### ISSUE TITLE
Figura Crashes when i press "/" to enter command in minecraft 1.16.5

### ISSUE THREAD

**Issue by SSAVN** [FiguraMC/Figura#242] opened 2024-07-20 10:27 UTC
### Bug Description

ye about the figura mod problem, when i press "/" to enter command in minecraft 1.16.5 the game go boom

### Reproduction Steps

i was create new mod pack and only use this one figura mod alone

and yes the game still crash when enter damn "/"

### Log File

[crash-2024-07-20_11.16.10-client.txt](https://github.com/user-attachments/files/16319776/crash-2024-07-20_11.16.10-client.txt)

**Comment by UnlikePaladin** [comment] 2024-07-20 13:45
Known issue, duplicate of #242
Please check open issues on the tracker before opening a new one. This issue was also fixed in the 0.1.5 release candidate which can be found on our discord or the release pages of this repository.

**Closed as completed** 2024-07-20 13:45 UTC
Labels: bug, duplicate, fixed
