### ISSUE TITLE
Compatibility issues with Embbedium

### ISSUE THREAD

**Issue by BlueFunny19** [FiguraMC/Figura#183] opened 2024-02-17 10:03 UTC
There seems to be some compatibility issues between Figura and Embeddium? I tried to use Embeddium together with the latest development version of Figura (0.1.3-pre4), but it still causes a crash on startup
Addendum: I'm using Minecarft 1.20.1, Forge 47.2.20 client
Here's my log: https://mclo.gs/4M9hc5e

**Comment by Covkie** [comment] 2024-02-17 10:39
seems to be a dupe of #176, closing.

**Closed as completed by Covkie** 2024-02-17 10:39 UTC
Labels: duplicate
