### ISSUE TITLE
Figura is crashing the client on startup 

### ISSUE THREAD

**Issue by euquinox** [FiguraMC/Figura#178] opened 2024-02-11 09:51 UTC
hi! whenever I add figura to my modpack it crashes the game on startup 
I wonder if it is incompatible with something? It has been like this since 1.19.2
thought the issue might've been fixed in 1.20.1 but unfortunately it keeps doing this 
[latest.log](https://github.com/FiguraMC/Figura/files/14231902/latest.log)

**Comment by KitCat962** [comment] 2024-02-11 14:36
Figura aims to be consistent across all minecraft versions, so thinking that Figura for mc 1.20.1 was released later than Figura for mc 1.19.2 is incorrect. They were released at the same time.
What truly matters is the version of Figura itself. I see you are using Figura 0.1.2 from the logs. Can you replace it with 0.1.3-pre4, downloadable from either the discord or github?

**Comment by euquinox** [comment] 2024-02-11 15:33
just tried that and I am still getting the same crash 
downloaded the file you mentioned from discord "figura-0.1.3-pre.41.20.1-forge-mc.jar" 
it doesn't show up on my modlist on curseforge since these versions obviously weren't uploaded yet 
maybe that's the issue now? I am not sure

**Comment by KitCat962** [comment] 2024-02-11 15:36
can you provide another log using pre4? The original log didnt provide anything useful and I'm hoping that with a new version something different will appear

**Comment by euquinox** [comment] 2024-02-11 15:40
sure!
[latest2.log](https://github.com/FiguraMC/Figura/files/14232923/latest2.log)
I quickly read through and it seems to be the same I might be wrong though

**Comment by KitCat962** [comment] 2024-02-11 15:44
yep, nothing.
I remember there was a mod combination that caused this kind of broken crash, but I cannot remember which mods.
I'm assuming the reason you are providing logs instead of crash reports is because there are no crash reports?
Push comes to shove, try figuring out which mod combinations are causing the crash by removing mods until the crashing stops

**Comment by euquinox** [comment] 2024-02-11 15:52
yea it just gives me exit code 1
alright, I'll try that and will let you know how it goes :]

**Comment by KitCat962** [comment] 2024-02-11 15:54
A crash report is an actual file, like how log files are actual files.
They are found in the crash reports folder in the .minecraft folder.

**Comment by euquinox** [comment] 2024-02-11 15:56
I know! but the latest crash report I have in that folder is from 3 days ago and it is the only one there
whenever the client crashes with figura I can only check the logs

**Comment by KitCat962** [comment] 2024-02-11 15:58
most people confuse the exit code to be a crash report, so I just wanted to clarify

**Comment by euquinox** [comment] 2024-02-11 16:06
it was oculus
should I submit this to their github or is it an issue on your end?
[2024-02-12-4.log](https://github.com/FiguraMC/Figura/files/14233048/2024-02-12-4.log)

**Comment by KitCat962** [comment] 2024-02-11 16:10
Ah, oculus. Known issue. Probably should, as we are compatible with iris fabric, but breaks with iris forge (which is named oculus)

**Comment by UnlikePaladin** [comment] 2024-02-19 01:11
Closing as dupe of #176

**Closed as completed by UnlikePaladin** 2024-02-19 01:11 UTC
Labels: bug, duplicate
